In [122]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

In [123]:
!pip install webdriver-manager

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Current google-chrome version is 95.0.4638
Get LATEST driver version for 95.0.4638

Requirement already satisfied: webdriver-manager in c:\users\sunil gupta\anaconda3\lib\site-packages (3.4.2)
Requirement already satisfied: crayons in c:\users\sunil gupta\anaconda3\lib\site-packages (from webdriver-manager) (0.4.0)
Requirement already satisfied: requests in c:\users\sunil gupta\anaconda3\lib\site-packages (from webdriver-manager) (2.24.0)
Requirement already satisfied: configparser in c:\users\sunil gupta\anaconda3\lib\site-packages (from webdriver-manager) (5.0.2)
Requirement already satisfied: colorama in c:\users\sunil gupta\anaconda3\lib\site-packages (from crayons->webdriver-manager) (0.4.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sunil gupta\anaconda3\lib\site-packages (from requests->webdriver-manager) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\sunil gupta\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sunil gupta\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\sunil gupta\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.25.11)

Driver [C:\Users\Sunil Gupta\.wdm\drivers\chromedriver\win32\95.0.4638.69\chromedriver.exe] found in cache

# Mobile

# a)

In [10]:
# opening the link
url = "https://www.flipkart.com/realme-narzo-50a-oxygen-blue-64-gb/product-reviews/itm81d679403c2b4?pid=MOBG6MY4UGGFQWYY&lid=LSTMOBG6MY4UGGFQWYYI8WMJQ&marketplace=FLIPKART"

In [11]:
driver.get(url)

In [12]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [13]:
time.sleep(3)
#scrapping the required details
start=0
end=49
for page in range(start,end):#for loop for scrapping 49 page
    mobile_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in mobile_star:
        star.append(i.text)#appending the text in Brand list
    mobile_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in mobile_short_review:
        short_review.append(i.text)#appending the description in list
    mobile_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in mobile_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [14]:
#creating a dataframe
df=pd.DataFrame({'mobile_star':star,
                'mobile_full_review':full_review,
                'mobile_short_review':short_review})
#printing dataframe
df

,mobile_star,mobile_full_review,mobile_short_review
0,4,Thanks again Flipkart team the wonderful deliv...,Very Good
1,4,Positive sides :\n1. Battery is very very powe...,Good choice
2,5,Excellent!!\nVery good mobile. I ordered it to...,Fantastic
3,5,Best phone superb design and colour and perfor...,Fabulous!
4,4,I bought it as a secondary device but was surp...,Nice product
...,...,...,...
370,5,I love filipcard,Terrific purchase
371,5,Very good phone\nVery very good delivery boy v...,Wonderful
372,1,Sharing my experience After using the month.\n...,Very poor
373,2,Camera poor quality,Expected a better product
374,5,Very nice,Great product

In [17]:
df.to_excel('mobile_comments1.xlsx',index=False)

# b)

In [18]:
# opening the link
url = "https://www.flipkart.com/poco-m3-yellow-64-gb/product-reviews/itmd1876d904897a?pid=MOBFZTCUPAHJVA94&lid=LSTMOBFZTCUPAHJVA94MERQ6U&marketplace=FLIPKART"

In [19]:
driver.get(url)

In [20]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [21]:
time.sleep(3)
#scrapping the required details
start=0
end=100
for page in range(start,end):#for loop for scrapping 100 page
    mobile_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in mobile_star:
        star.append(i.text)#appending the text in Brand list
    mobile_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in mobile_short_review:
        short_review.append(i.text)#appending the description in list
    mobile_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in mobile_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [22]:
#creating a dataframe
df=pd.DataFrame({'mobile_star':star,
                'mobile_full_review':full_review,
                'mobile_short_review':short_review})
#printing dataframe
df

,mobile_star,mobile_full_review,mobile_short_review
0,5,Great Phone at this Price point. Superb cool D...,Highly recommended
1,4,"Good mobile poco m3\nPros:\nFullhd display,\ns...",Really Nice
2,5,Good phone battery🔋 And camera This price poin...,Wonderful
3,5,U will never get this specs for this price...d...,Mind-blowing purchase
4,5,"One word review "" Value for Money""\nIt has the...",Terrific
...,...,...,...
995,3,Good phone but its camera is avarage,Nice
996,5,Good battery backup,Perfect product!
997,3,Battery and display are good. But camera is wo...,Decent product
998,5,Nice but poco m2 is good and better performanc...,Awesome
999,2,"It has more heating effect , large display , s...",Bad quality

In [23]:
df.to_excel('mobile_comments2.xlsx',index=False)

# c)

In [24]:
# opening the link
url = "https://www.flipkart.com/infinix-hot-10-play-7-purple-32-gb/product-reviews/itm1f660c8716944?pid=MOBG4ZY7ADYFEJ3H&lid=LSTMOBG4ZY7ADYFEJ3HZ0AJER&marketplace=FLIPKART"

In [25]:
driver.get(url)

In [26]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [27]:
time.sleep(3)
#scrapping the required details
start=0
end=33
for page in range(start,end):#for loop for scrapping 33 page
    mobile_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in mobile_star:
        star.append(i.text)#appending the text in Brand list
    mobile_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in mobile_short_review:
        short_review.append(i.text)#appending the description in list
    mobile_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in mobile_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [28]:
#creating a dataframe
df=pd.DataFrame({'mobile_star':star,
                'mobile_full_review':full_review,
                'mobile_short_review':short_review})
#printing dataframe
df

,mobile_star,mobile_full_review,mobile_short_review
0,3,Battery : is best\nDisplay : Perfect\nSound : ...,Does the job
1,5,I bought this smartphone for my friend. I hope...,Wonderful
2,4,This mobil is very nice.\nThe rear camera is f...,Good quality product
3,3,This phone has large display with some good fe...,Nice
4,4,i had booked this mobile call and i got it tod...,Pretty good
...,...,...,...
188,4,Good performance product,Delightful
189,5,It is very amazing\n😍 phone,Fabulous!
190,5,Good,Terrific purchase
191,5,Nice phone e everything is good,Highly recommended
192,5,"Best price, so long display",Great product

In [29]:
df.to_excel('mobile_comments3.xlsx',index=False)

# d)

In [40]:
# opening the link
url = "https://www.flipkart.com/infinix-smart-5a-midnight-black-32-gb/product-reviews/itma0d1e81b14743?pid=MOBG56UGBGFN9JRN&lid=LSTMOBG56UGBGFN9JRN7VONX0&marketplace=FLIPKART"

In [41]:
driver.get(url)

In [42]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [43]:
time.sleep(3)
#scrapping the required details
start=0
end=40
for page in range(start,end):#for loop for scrapping 40 page
    mobile_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in mobile_star:
        star.append(i.text)#appending the text in Brand list
    mobile_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in mobile_short_review:
        short_review.append(i.text)#appending the description in list
    mobile_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in mobile_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [44]:
#creating a dataframe
df=pd.DataFrame({'mobile_star':star,
                'mobile_full_review':full_review,
                'mobile_short_review':short_review})
#printing dataframe
df

,mobile_star,mobile_full_review,mobile_short_review
0,4,Writing review after using for a week\nBought ...,Wonderful
1,5,Sharp and crisp display.. not very heavy despi...,Best in the market!
2,5,It's a amazing deal...such a featured mobile a...,Excellent
3,5,Worth of money . performance good and all thin...,Classy product
4,5,Infinix mobile quality better and battery pick...,Excellent
...,...,...,...
316,5,Very nice,Highly recommended
317,3,Ok,Good
318,3,Good phone,Decent product
319,5,"Worth for money, good performance",Mind-blowing purchase
320,5,Overall good,Terrific

In [45]:
df.to_excel('mobile_comments4.xlsx',index=False)

# laptop
#### a)

In [46]:
# opening the link
url = "https://www.flipkart.com/asus-celeron-dual-core-4-gb-1-tb-hdd-windows-10-home-x543ma-gq1015t-laptop/product-reviews/itmf8811674edbeb?pid=COMFSKF9UQH8RKYF&lid=LSTCOMFSKF9UQH8RKYFK8UKIL&marketplace=FLIPKART"

In [47]:
driver.get(url)

In [48]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [49]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [50]:
#creating a dataframe
df=pd.DataFrame({'Number of Laptop Stars':star,
                'Laptop_Full_Review':full_review,
                'Laptop_Short_Review':short_review})
#printing dataframe
df

,Number of Laptop Stars,Laptop_Full_Review,Laptop_Short_Review
0,5,It's very good to this price.....I really than...,Simply awesome
1,5,Performance are too good and friendly budget a...,Fabulous!
2,5,Seriously awwsm .. pls go for it without any h...,Great product
3,4,I am happy with this laptop. Good for basic us...,Nice product
4,5,I have just received the laptop today and am v...,Great product
...,...,...,...
792,5,Very good,Super!
793,5,Quality is excellent,Simply awesome
794,5,Good performance for such a low price.Delivere...,Classy product
795,3,Good light weight laptop. perfect for kids onl...,Decent product
796,5,Rating this after 4 days... According to price...,Highly recommended

In [52]:
df.to_excel('laptop_comments1.xlsx',index=False)

# b)

In [53]:
# opening the link
url = "https://www.flipkart.com/acer-aspire-7-core-i5-10th-gen-8-gb-512-gb-ssd-windows-10-home-4-graphics-nvidia-geforce-gtx-1650-a715-75g-50ta-a715-75g-41g-gaming-laptop/product-reviews/itmc97c3da5d2abe?pid=COMG2KBG2K4GFFF7&lid=LSTCOMG2KBG2K4GFFF78YBPHO&marketplace=FLIPKART"

In [54]:
driver.get(url)

In [55]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [56]:
time.sleep(3)
#scrapping the required details
start=0
end=40
for page in range(start,end):#for loop for scrapping 40 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [57]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,5,Just wow!,"Good Product, I am satisfied all of the featur..."
1,5,Wonderful,Performance is good as I expect in this price ...
2,5,Great product,Amazing laptop. It has a premium and professio...
3,5,Awesome,It's really a nice laptop🤩🤩....I got it for 49...
4,3,Good,"So basically, laptop is well and good. But the..."
...,...,...,...
318,5,Fabulous!,Overall product is good\nBut battery backup is...
319,5,Awesome,very good product.
320,5,Great product,This laptop 💻 very good product
321,5,Terrific,Loved it ❤️❤️
322,3,Just okay,Best 👍🏻👍🏻👍🏻

In [58]:
df.to_excel('laptop_comments2.xlsx',index=False)

# c)

In [59]:
# opening the link
url = "https://www.flipkart.com/asus-vivobook-ultra-14-core-i3-10th-gen-4-gb-512-gb-ssd-windows-10-home-x413ja-ek267t-x413ja-eb302t-thin-light-laptop/product-reviews/itm1cb0d9da56a94?pid=COMFTWZD9Z8VVABB&lid=LSTCOMFTWZD9Z8VVABBA4VHKD&marketplace=FLIPKART&page=1"

In [60]:
driver.get(url)

In [61]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [62]:
time.sleep(3)
#scrapping the required details
start=0
end=45
for page in range(start,end):#for loop for scrapping 45 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [63]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,5,Just wow!,After one month of use ASUS VIVOBOOK 14/15 i3 ...
1,5,Mind-blowing purchase,"I was in confusion before order, when I receiv..."
2,4,Good choice,"Reviewing after 4 months of use, It's a good b..."
3,5,Worth every penny - Go for it.,After using 15 days I would say product is goo...
4,4,Nice product,Best compact laptop but build quality is not m...
...,...,...,...
445,4,Wonderful,average product
446,5,Awesome,"It's good, for normal use performance is good,..."
447,4,Worth the money,Great option indeed. You can spend you wont re...
448,5,Brilliant,Superbbbbbbbb
449,4,Worth the money,Good buttery smooth performance because of the...

In [64]:
df.to_excel('laptop_comments3.xlsx',index=False)

# d)

In [65]:
# opening the link
url = "https://www.flipkart.com/acer-aspire-7-core-i5-10th-gen-8-gb-512-gb-ssd-windows-10-home-4-graphics-nvidia-geforce-gtx-1650-a715-75g-50ta-a715-75g-41g-gaming-laptop/product-reviews/itmc97c3da5d2abe?pid=COMG2KBG2K4GFFF7&lid=LSTCOMG2KBG2K4GFFF78YBPHO&marketplace=FLIPKART"

In [66]:
driver.get(url)

In [67]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [68]:
time.sleep(3)
#scrapping the required details
start=0
end=50
for page in range(start,end):#for loop for scrapping 50 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [69]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,5,Just wow!,"Good Product, I am satisfied all of the featur..."
1,5,Wonderful,Performance is good as I expect in this price ...
2,5,Great product,Amazing laptop. It has a premium and professio...
3,5,Awesome,It's really a nice laptop🤩🤩....I got it for 49...
4,3,Good,"So basically, laptop is well and good. But the..."
...,...,...,...
387,5,Classy product,Good product but battery is not so good
388,5,Perfect product!,Nice
389,5,Terrific,NICE PRODUCT
390,4,Very Good,Good hardware with average display
391,4,Really Nice,"very value for money, but there is a problem t..."

In [70]:
df.to_excel('laptop_comments4.xlsx',index=False)

# e)

In [71]:
# opening the link
url = "https://www.flipkart.com/asus-vivobook-ultra-14-core-i3-10th-gen-4-gb-512-gb-ssd-windows-10-home-x413ja-ek267t-x413ja-eb302t-thin-light-laptop/product-reviews/itm1cb0d9da56a94?pid=COMFTWZD9Z8VVABB&lid=LSTCOMFTWZD9Z8VVABBA4VHKD&marketplace=FLIPKART"

In [72]:
driver.get(url)

In [73]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [74]:
time.sleep(3)
#scrapping the required details
start=0
end=42
for page in range(start,end):#for loop for scrapping 42 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [75]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,5,Just wow!,After one month of use ASUS VIVOBOOK 14/15 i3 ...
1,5,Mind-blowing purchase,"I was in confusion before order, when I receiv..."
2,4,Good choice,"Reviewing after 4 months of use, It's a good b..."
3,5,Worth every penny - Go for it.,After using 15 days I would say product is goo...
4,4,Nice product,Best compact laptop but build quality is not m...
...,...,...,...
415,5,Perfect product!,excellent service boy
416,4,Good choice,Looking so nice and pretty
417,4,Pretty good,Screen is the only thing holding it back...\nH...
418,5,Simply awesome,"Got delivered early , looks good on first impr..."
419,3,Just okay,Display size is too short

In [76]:
df.to_excel('laptop_comments5.xlsx',index=False)

# f)

In [77]:
# opening the link
url = "https://www.flipkart.com/asus-tuf-gaming-f15-core-i5-10th-gen-8-gb-512-gb-ssd-windows-10-home-4-graphics-nvidia-geforce-gtx-1650-144-hz-fx506lh-hn258t-laptop/product-reviews/itm834e03127f443?pid=COMGFVWMDZPGK4WR&lid=LSTCOMGFVWMDZPGK4WRWRM8ES&marketplace=FLIPKART"

In [78]:
driver.get(url)

In [79]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [80]:
time.sleep(3)
#scrapping the required details
start=0
end=28
for page in range(start,end):#for loop for scrapping 28 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [82]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,5,Awesome,One of the best Laptop in this range. It is be...
1,4,Wonderful,It is working like a beast but battery is some...
2,5,Terrific,Writing this review after 2 weeks of usage\n\n...
3,4,Review after excessive use of 7 days.,No cost EMI option is a plus point given by Fl...
4,5,Simply awesome,Got this for 61k. Great value for money. Best ...
...,...,...,...
275,5,Simply awesome,Awesome performance
276,5,Brilliant,Smooth work & good
277,5,Fabulous!,Awsm
278,5,Best in the market!,Good
279,5,Classy product,Awesome

In [83]:
df.to_excel('laptop_comments6.xlsx',index=False)

# f)

In [3]:
# opening the link
url = "https://www.flipkart.com/asus-pentium-quad-core-4-gb-1-tb-hdd-windows-10-home-x543ma-gq1020t-laptop/product-reviews/itmc21cd172b84ea?pid=COMFSKF9DHVPZCYZ&lid=LSTCOMFSKF9DHVPZCYZTR5RZ0&marketplace=FLIPKART"

In [4]:
driver.get(url)

In [5]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [6]:
time.sleep(3)
#scrapping the required details
start=0
end=52
for page in range(start,end):#for loop for scrapping 52 page
    laptop_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in laptop_star:
        star.append(i.text)#appending the text in Brand list
    laptop_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in laptop_short_review:
        short_review.append(i.text)#appending the description in list
    laptop_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in laptop_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [7]:
#Combining all the lists into a single dataframe
df=pd.DataFrame({'Number of Laptop Stars': star,
                'Laptop Short Review': short_review,
               'Laptop Full Review': full_review})
df

,Number of Laptop Stars,Laptop Short Review,Laptop Full Review
0,4,Nice product,"Good for online class , pdf reading, excel,ppt..."
1,4,Pretty good,I used more than one week it's good for light ...
2,4,Very Good,"Best price with Intel processor, performance i..."
3,5,Fabulous!,Low proccesor\nBut good for studying and daily...
4,4,Really Nice,initially I had trouble with the charger. howe...
...,...,...,...
515,3,Does the job,Good product average performance good for stud...
516,1,Don't waste your money,Very very slow processer don't buy
517,5,Worth every penny,Review after 7 days of use...\nBATTERY.. Upto ...
518,1,Worthless,Slow very slow
519,5,Fabulous!,Nice product

In [8]:
df.to_excel('laptop_comments7.xlsx',index=False)

# Headphones

## A)

In [9]:
# opening the link
url = "https://www.flipkart.com/boult-audio-probass-xcharge-fast-charging-bluetooth-headset/product-reviews/itm26894519dd3fc?pid=ACCG3HY9ZNDBZDKS&lid=LSTACCG3HY9ZNDBZDKSCOK3CI&marketplace=FLIPKART"

In [10]:
driver.get(url)

In [11]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [12]:
time.sleep(3)
#scrapping the required details
start=0
end=70
for page in range(start,end):#for loop for scrapping 70 page
    headphone_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in headphone_star:
        star.append(i.text)#appending the text in Brand list
    headphone_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in headphone_short_review:
        short_review.append(i.text)#appending the description in list
    headphone_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in headphone_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [13]:
#creating a dataframe
df=pd.DataFrame({'Headphone_star':star,
                'Headphone_full_review':full_review,
                'Headphone_short_review':short_review})
#printing dataframe
df

,Headphone_star,Headphone_full_review,Headphone_short_review
0,5,Using this product for the past 10 days or mor...,Brilliant
1,5,The sound quality of the neckband is just awes...,Best in the market!
2,5,This is my first ever purchase of Boult produc...,Simply awesome
3,5,Bettry backup is just awesome . To just check ...,Fabulous!
4,5,It sounds excellent in its battery backup. It ...,Best in the market!
...,...,...,...
322,5,Really good & nice product,Simply awesome
323,2,Sound quality bad,Expected a better product
324,4,"Best mixing Sound output, bass is quite loud,",Pretty good
325,5,Good but battery issue,Fabulous!
326,5,Good product,Classy product

In [14]:
df.to_excel('headphone_comments1.xlsx',index=False)

## b)

In [15]:
# opening the link
url = "https://www.flipkart.com/mivi-collar-classic-neckband-fast-charging-bluetooth-headset/product-reviews/itm2005b6fa9cd7b?pid=ACCGFGJTGWRHZUAF&lid=LSTACCGFGJTGWRHZUAFQLSOH2&marketplace=FLIPKART"

In [16]:
driver.get(url)

In [17]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [18]:
time.sleep(3)
#scrapping the required details
start=0
end=50
for page in range(start,end):#for loop for scrapping 50 page
    headphone_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in headphone_star:
        star.append(i.text)#appending the text in Brand list
    headphone_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in headphone_short_review:
        short_review.append(i.text)#appending the description in list
    headphone_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in headphone_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [19]:
#creating a dataframe
df=pd.DataFrame({'Headphone_star':star,
                'Headphone_full_review':full_review,
                'Headphone_short_review':short_review})
#printing dataframe
df

,Headphone_star,Headphone_full_review,Headphone_short_review
0,5,This collar earphones is really good in sound ...,Brilliant
1,5,Best product of Mivi. Enjoying listening music...,Great product
2,5,So Now I received my first mivi product.\nThe ...,Super!
3,5,Value for money!!\n\nGot it delivered within 3...,Great product
4,4,Definitely a good pick for the price. The soun...,Delightful
...,...,...,...
495,5,Good 👍👍,Mind-blowing purchase
496,5,Value for money,Just wow!
497,5,After using about 6 months I m writing this fe...,Great product
498,5,Great,Simply awesome
499,5,Awesome thanks so much,Worth every penny

In [20]:
df.to_excel('headphone_comments2.xlsx',index=False)

# C)

In [21]:
# opening the link
url = "https://www.flipkart.com/catbull-in-ear-bluetooth-headset/product-reviews/itm72ac06288fd80?pid=ACCFS8HHZSEDBVDC&lid=LSTACCFS8HHZSEDBVDCWYZK0Q&marketplace=FLIPKART&page=1"

In [22]:
driver.get(url)

In [23]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [24]:
time.sleep(3)
#scrapping the required details
start=0
end=35
for page in range(start,end):#for loop for scrapping 35 page
    headphone_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLP'
    for i in headphone_star:
        star.append(i.text)#appending the text in Brand list
    headphone_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in headphone_short_review:
        short_review.append(i.text)#appending the description in list
    headphone_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in headphone_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [25]:
#creating a dataframe
df=pd.DataFrame({'Headphone_star':star,
                'Headphone_full_review':full_review,
                'Headphone_short_review':short_review})
#printing dataframe
df

,Headphone_star,Headphone_full_review,Headphone_short_review
0,4,"Pros,\n1. Good neckband at a decent price\n2. ...",Nice product
1,5,Awesome Bluetooth super sound and super bass b...,Mind-blowing purchase
2,3,It's ok for the price. The build quality is ac...,Does the job
3,3,It is a good product\nBut sound quality is ave...,Decent product
4,5,This earphone is best for some works because i...,Perfect product!
...,...,...,...
328,5,Good product 😂,Mind-blowing purchase
329,3,Nice,Just okay
330,1,Veri Veri bad,Worthless
331,5,Excillent,Wonderful
332,5,Thanks,Worth every penny

In [26]:
df.to_excel('headphone_comments3.xlsx',index=False)

# D)

In [31]:
# opening the link
url = "https://www.flipkart.com/oneplus-bullets-wireless-z-bass-bluetooth-headset/product-reviews/itmc804703e0785e?pid=ACCFVA3KZ2EYMYX3&lid=LSTACCFVA3KZ2EYMYX3C5TCKH&marketplace=FLIPKART"

In [32]:
driver.get(url)

In [33]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [34]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    headphone_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in headphone_star:
        star.append(i.text)#appending the text in Brand list
    headphone_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in headphone_short_review:
        short_review.append(i.text)#appending the description in list
    headphone_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in headphone_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [35]:
#creating a dataframe
df=pd.DataFrame({'Headphone_star':star,
                'Headphone_full_review':full_review,
                'Headphone_short_review':short_review})
#printing dataframe
df

,Headphone_star,Headphone_full_review,Headphone_short_review
0,5,Good battery 🔋 👌\nSound awesome 👌\nBass 🔊 supe...,Highly recommended
1,5,This is my first OnePlus product and now I'm i...,Excellent
2,5,I've been using this product for the last 3 da...,Great product
3,5,Awesome product..... With a super deep bass an...,Super!
4,5,Very nice product with amazing battery back up...,Super!
...,...,...,...
795,5,It's good,Must buy!
796,1,Bad,Absolute rubbish!
797,1,Sound quality is good but seller service is to...,Don't waste your money
798,1,It's battery is some what ok but sound quality...,Don't waste your money
799,1,Bad,Unsatisfactory

In [37]:
df.to_excel('headphone_comments4.xlsx',index=False)

# E)

In [40]:
# opening the link
url = "https://www.flipkart.com/oxhox-magnetic-bluetooth-headset-mic/product-reviews/itm5b155ee91919f?pid=ACCFGKU8GPU5T8BH&lid=LSTACCFGKU8GPU5T8BHUMIN0X&marketplace=FLIPKART"

In [41]:
driver.get(url)

In [42]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [43]:
time.sleep(3)
#scrapping the required details
start=0
end=40
for page in range(start,end):#for loop for scrapping 40 page
    headphone_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in headphone_star:
        star.append(i.text)#appending the text in Brand list
    headphone_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in headphone_short_review:
        short_review.append(i.text)#appending the description in list
    headphone_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in headphone_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [44]:
#creating a dataframe
df=pd.DataFrame({'Headphone_star':star,
                'Headphone_full_review':full_review,
                'Headphone_short_review':short_review})
#printing dataframe
df

,Headphone_star,Headphone_full_review,Headphone_short_review
0,5,"Super design fit for ears, Mike is awesome com...",Fabulous!
1,5,Very awesome as I received as expected. Same a...,Classy product
2,5,Very good product. The sound is little a bit l...,Awesome
3,3,The best product and high base and Sound clari...,Good
4,4,very good product sound quality and bass was g...,Really Nice
...,...,...,...
385,2,Quality is not good this this is West product ...,Bad quality
386,5,Good product very nice,Great product
387,1,This is the chip headset,Not recommended at all
388,3,So nice,Nice
389,5,Nice sound player,Super!

In [45]:
df.to_excel('headphone_comments5.xlsx',index=False)

# Monitors

### a)

In [46]:
# opening the link
url = "https://www.flipkart.com/lg-18-5-inches-hd-led-backlit-tn-panel-monitor-19m38ab/product-reviews/itmeuchf5jfmqw8x?pid=MONEUCHFCQUFRSPD&lid=LSTMONEUCHFCQUFRSPDWPNOTD&marketplace=FLIPKART"

In [47]:
driver.get(url)

In [49]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [50]:
time.sleep(3)
#scrapping the required details
start=0
end=70
for page in range(start,end):#for loop for scrapping 70 page
    monitor_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in monitor_star:
        star.append(i.text)#appending the text in Brand list
    monitor_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in monitor_short_review:
        short_review.append(i.text)#appending the description in list
    monitor_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in monitor_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [52]:
#creating a dataframe
df=pd.DataFrame({'Monitor_Star':star,
                'Monitor_Full_Review':full_review,
                'Monitor_Short_Review':short_review})
#printing dataframe
df

,Monitor_Star,Monitor_Full_Review,Monitor_Short_Review
0,5,well.....Ist of all package was mind blowing s...,Wonderful
1,5,LG monitor is very good it is budget segment m...,Awesome
2,5,nice product and beautiful monitor 😍😍 very cle...,Wonderful
3,4,I like thz product. Low cost and wide screen. ...,Really Nice
4,5,This monitor is good and enough for daily use....,Mind-blowing purchase
...,...,...,...
695,5,Very useful in this price 5199/-,Brilliant
696,1,Good,Classy product
697,5,Excellent!!,Excellent
698,1,"Very Bad product in my view, want to return bu...",Very poor
699,5,nic,Mind-blowing purchase

In [54]:
df.to_excel('monitor_comments1.xlsx',index=False)

# b)

In [58]:
# opening the link
url = "https://www.flipkart.com/acer-19-5-inch-hd-led-backlit-tn-panel-monitor-v206hql/product-reviews/itmeygcwhszg2vfh?pid=MONEYGCHK5GHSN6B&lid=LSTMONEYGCHK5GHSN6BEC82ID&marketplace=FLIPKART"

In [59]:
driver.get(url)

In [60]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [61]:
time.sleep(3)
#scrapping the required details
start=0
end=83
for page in range(start,end):#for loop for scrapping 83 page
    monitor_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in monitor_star:
        star.append(i.text)#appending the text in Brand list
    monitor_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in monitor_short_review:
        short_review.append(i.text)#appending the description in list
    monitor_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in monitor_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [62]:
#creating a dataframe
df=pd.DataFrame({'Monitor_Star':star,
                'Monitor_Full_Review':full_review,
                'Monitor_Short_Review':short_review})
#printing dataframe
df

,Monitor_Star,Monitor_Full_Review,Monitor_Short_Review
0,4,"good product , sound need to be improved , sou...",Delightful
1,3,Pros - Slim border line style. Lightweight & c...,Medium quality
2,5,The product was great I am loving it and it's ...,Simply awesome
3,4,Happy With the quick delivery of flipkart. But...,Nice product
4,5,Amazing work good quality display mind-blowing...,Highly recommended
...,...,...,...
821,3,It is not HD LED monitor. It is LCD monitor an...,Just okay
822,5,Excellent,Wonderful
823,5,Absolutely Good Monitor Big screen,Classy product
824,1,Waste product don't by this monitor. Instead o...,Don't waste your money
825,4,Overall very good product in this price range....,Nice product

In [64]:
df.to_excel('monitor_comments2.xlsx',index=False)

# c)

In [72]:
# opening the link
url = "https://www.flipkart.com/samsung-23-8-inch-curved-full-hd-led-backlit-va-panel-monitor-lc24f390fhwxxl/product-reviews/itmezu53yhwg2ayg?pid=MONEZU4Z8BYBV2GZ&lid=LSTMONEZU4Z8BYBV2GZCQOCQM&marketplace=FLIPKART"

In [73]:
driver.get(url)

In [74]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [75]:
time.sleep(3)
#scrapping the required details
start=0
end=40
for page in range(start,end):#for loop for scrapping 40 page
    monitor_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in monitor_star:
        star.append(i.text)#appending the text in Brand list
    monitor_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in monitor_short_review:
        short_review.append(i.text)#appending the description in list
    monitor_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in monitor_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [76]:
#creating a dataframe
df=pd.DataFrame({'Monitor_Star':star,
                'Monitor_Full_Review':full_review,
                'Monitor_Short_Review':short_review})
#printing dataframe
df

,Monitor_Star,Monitor_Full_Review,Monitor_Short_Review
0,5,First of all I would like to thank Flipkart fo...,Great product at this price range
1,5,Best product in affordable price. Very satisfy...,Excellent
2,1,"After I read all the reviews and ratings, I de...",Terrible product
3,5,A new experience. It's a very good monitor. My...,Perfect product!
4,5,This monitor has an excellent display and the ...,Best in this price range.
...,...,...,...
395,5,true value for money.. fast and prompt deliver...,Best in the market!
396,5,The best monitor you can ever buy. Price is ve...,Just wow!
397,5,Total Value for Money,Should give a try
398,4,New experience with LED\n\nGood quality and aw...,Good quality product
399,5,"Awesome product, love at first sight. Recommen...",Fabulous!

In [77]:
df.to_excel('monitor_comments3.xlsx',index=False)

# d)

In [78]:
# opening the link
url = "https://www.flipkart.com/samsung-23-5-inch-full-hd-ips-panel-monitor-ls24f350fhwxxl/product-reviews/itmf57d5p5pgjnss?pid=MONF577ZTAZEUYRH&lid=LSTMONF577ZTAZEUYRHZWS0EU&marketplace=FLIPKART"

In [79]:
driver.get(url)

In [80]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [82]:
time.sleep(3)
#scrapping the required details
start=0
end=9
for page in range(start,end):#for loop for scrapping 9 page
    monitor_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in monitor_star:
        star.append(i.text)#appending the text in Brand list
    monitor_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in monitor_short_review:
        short_review.append(i.text)#appending the description in list
    monitor_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in monitor_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [83]:
#creating a dataframe
df=pd.DataFrame({'Monitor_Star':star,
                'Monitor_Full_Review':full_review,
                'Monitor_Short_Review':short_review})
#printing dataframe
df

,Monitor_Star,Monitor_Full_Review,Monitor_Short_Review
0,4,"Nice product, with 3 yrs warranty from Samsung...",Pretty good
1,5,Excellent Monitor!\nBeautiful and crisp pictur...,Brilliant
2,5,big enough for architectural work and even gam...,Worth every penny
3,5,Good,Super!
4,5,"large display , clear view ,matte finish, smoo...",Perfect product!
...,...,...,...
123,5,awesome,Super!
124,4,Nice Product you can buy this.,Very Good
125,5,worth its price,Terrific purchase
126,5,very good protect,Perfect product!
127,5,asam,Classy product

In [85]:
df.to_excel('monitor_comments4.xlsx',index=False)

# e)

In [86]:
# opening the link
url = "https://www.flipkart.com/lg-18-5-inches-hd-led-backlit-tn-panel-monitor-19m38ab/product-reviews/itmeuchf5jfmqw8x?pid=MONEUCHFCQUFRSPD&lid=LSTMONEUCHFCQUFRSPDWPNOTD&marketplace=FLIPKART"

In [87]:
driver.get(url)

In [88]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [89]:
time.sleep(3)
#scrapping the required details
start=0
end=25
for page in range(start,end):#for loop for scrapping 25 page
    monitor_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in monitor_star:
        star.append(i.text)#appending the text in Brand list
    monitor_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in monitor_short_review:
        short_review.append(i.text)#appending the description in list
    monitor_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in monitor_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [90]:
#creating a dataframe
df=pd.DataFrame({'Monitor_Star':star,
                'Monitor_Full_Review':full_review,
                'Monitor_Short_Review':short_review})
#printing dataframe
df

,Monitor_Star,Monitor_Full_Review,Monitor_Short_Review
0,5,well.....Ist of all package was mind blowing s...,Wonderful
1,5,LG monitor is very good it is budget segment m...,Awesome
2,5,nice product and beautiful monitor 😍😍 very cle...,Wonderful
3,4,I like thz product. Low cost and wide screen. ...,Really Nice
4,5,This monitor is good and enough for daily use....,Mind-blowing purchase
...,...,...,...
245,5,GooD,Mind-blowing purchase
246,5,Good to use.\n\nClear Image.,Simply awesome
247,5,nice,Best in the market!
248,5,this product is very nice .the most coolers fu...,Terrific purchase
249,5,Quality product within the range. Picture qual...,Wonderful

In [92]:
df.to_excel('monitor_comments5.xlsx',index=False)

# Home theater

# a)

In [93]:
# opening the link
url = "https://www.flipkart.com/sony-sa-d40-80-w-bluetooth-home-theatre/product-reviews/itmfy95dvfgcbnsd?pid=ACCFY95D3FRZTWH5&lid=LSTACCFY95D3FRZTWH5XCIMPG&marketplace=FLIPKART"

In [94]:
driver.get(url)

In [95]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [96]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    Home_theater_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLP'
    for i in Home_theater_star:
        star.append(i.text)#appending the text in Brand list
    Home_theater_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Home_theater_short_review:
        short_review.append(i.text)#appending the description in list
    Home_theater_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Home_theater_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [97]:
#creating a dataframe
df=pd.DataFrame({'Home_theater_Star':star,
                'Home_theater_Full_Review':full_review,
                'Home_theater_Short_Review':short_review})
#printing dataframe
df

,Home_theater_Star,Home_theater_Full_Review,Home_theater_Short_Review
0,5,sony D40 80 waat home theatre is so awsm..I bo...,Simply awesome
1,5,nice product awesome bass sound quality supb. ...,Just wow!
2,3,1. Bass is very powerful\n2.sound clarity is a...,Nice product
3,5,"it's Really Awsome Product , I Satisfied too m...",Terrific
4,2,don't buy if you are willing to connect it to ...,Not good
...,...,...,...
765,5,"Excellent product just blindly have it, as I s...",Terrific
766,5,Value for money,Fabulous!
767,5,Nice product 👍👍👍,Must buy!
768,5,Great product a one 😄😄😄,Must buy!
769,4,Bass is tooo much high,Pretty good

In [98]:
df.to_excel('home_theatre_comments1.xlsx',index=False)

# b)

In [99]:
# opening the link
url = "https://www.flipkart.com/zebronics-indie-105-w-bluetooth-home-theatre/product-reviews/itm425bfd9d619b7?pid=ACCF3BHUWH7EBV78&lid=LSTACCF3BHUWH7EBV78LPUEHH&marketplace=FLIPKART"

In [100]:
driver.get(url)

In [101]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [102]:
time.sleep(3)
#scrapping the required details
start=0
end=100
for page in range(start,end):#for loop for scrapping 100 page
    Home_theater_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in Home_theater_star:
        star.append(i.text)#appending the text in Brand list
    Home_theater_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Home_theater_short_review:
        short_review.append(i.text)#appending the description in list
    Home_theater_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Home_theater_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [103]:
#creating a dataframe
df=pd.DataFrame({'Home_theater_Star':star,
                'Home_theater_Full_Review':full_review,
                'Home_theater_Short_Review':short_review})
#printing dataframe
df

,Home_theater_Star,Home_theater_Full_Review,Home_theater_Short_Review
0,5,"Mindblowing Awesome bass, just Boom the Room w...",Just wow!
1,5,"Awsome audio quality ,bass quality is good and...",Excellent
2,5,I bought it for my father as an anniversary gi...,Brilliant
3,5,No other choices... Please buy it.. Superb and...,Great product
4,5,Just Beyond Expectation ! 🤩\ni) Terrific Sound...,Awesome
...,...,...,...
991,5,Nice products,Awesome
992,5,"Just Go for blindly, it's rocking...Real sound...",Highly recommended
993,5,Very good product 👍,Just wow!
994,5,Good👌👌👌,Worth every penny
995,5,Great product...must buy.!,Must buy!

In [104]:
df.to_excel('home_theatre_comments2.xlsx',index=False)

# c)

In [105]:
# opening the link
url = "https://www.flipkart.com/philips-spa8140b-94-38-w-bluetooth-home-theatre/product-reviews/itmex3yybthtgttg?pid=ACCEX3YYQMVCGVYS&lid=LSTACCEX3YYQMVCGVYSXSUYFY&marketplace=FLIPKART"

In [106]:
driver.get(url)

In [107]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [108]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    Home_theater_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in Home_theater_star:
        star.append(i.text)#appending the text in Brand list
    Home_theater_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Home_theater_short_review:
        short_review.append(i.text)#appending the description in list
    Home_theater_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Home_theater_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [120]:
#creating a dataframe
df=pd.DataFrame({'Home_theater_Star':star,
                'Home_theater_Full_Review':full_review,
                'Home_theater_Short_Review':short_review})
#printing dataframe
df

,Home_theater_Star,Home_theater_Full_Review,Home_theater_Short_Review
0,5,Great Value for money !! Good product + Great ...,#VALUEforMONEY
1,5,It's an Awesome Product at Reasonable price an...,Fabulous!
2,5,wonderful in low voltage also comes good sound...,Excellent
3,5,Nice product with stylish and with nice sound....,Brilliant
4,5,Awesome......I got it for 3550 in sale and m s...,Awesome
...,...,...,...
779,5,Everything ok..... pure sounds quality.....but...,Highly recommended
780,3,Not that great sound u can only buy for blue t...,Nice
781,5,Awesome product........,Highly recommended
782,5,super,Terrific purchase
783,4,Nice Product...,Worth the money

In [109]:
df.to_excel('home_theatre_comments3.xlsx',index=False)

# Router

# A)

In [12]:
# opening the link
url = "https://www.flipkart.com/tp-link-archer-c20-750-mbps-wireless-router/product-reviews/itmebwva79qghyk9?pid=RTRE8GKF2CUJ2GNN&lid=LSTRTRE8GKF2CUJ2GNNA9BJX3&marketplace=FLIPKART"

In [13]:
driver.get(url)

In [14]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [117]:
time.sleep(3)
#scrapping the required details
start=0
end=120
for page in range(start,end):#for loop for scrapping 120 page
    Router_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in Router_star:
        star.append(i.text)#appending the text in Brand list
    Router_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Router_short_review:
        short_review.append(i.text)#appending the description in list
    Router_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Router_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [118]:
#creating a dataframe
df=pd.DataFrame({'Router_star':star,
                'Router_full_review':full_review,
                'Router_short_review':short_review})
#printing dataframe
df

,Router_star,Router_full_review,Router_short_review
0,5,This is the best WiFi router in this price ran...,Worth every penny
1,5,"Just fabulous performance, i am very glad to c...",Wonderful
2,5,If you want a router for medium sized Flat/hom...,Got a good router after doing a lot of research!
3,5,Compact and good looking router.\nTwo external...,Very Good Router
4,4,Does the job. It is good for 2 BHK home usage....,Worth the money
...,...,...,...
1177,5,Good product,Just wow!
1178,5,Good product,Perfect product!
1179,5,Using this router for past 20 days. My experie...,Terrific purchase
1180,5,Best service thanks flipkart...,Classy product
1181,5,Best wifi router for bsnl ftth,Terrific

In [119]:
df.to_excel('Router_comments1.xlsx',index=False)

# b)

In [15]:
# opening the link
url = "https://www.flipkart.com/d-link-dir-819-750-mbps-wireless-router/product-reviews/itmff2hynmhzhtqa?pid=RTRFF2HYYUYHCGGK&lid=LSTRTRFF2HYYUYHCGGKB3BKOG&marketplace=FLIPKART"

In [16]:
driver.get(url)

In [17]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [18]:
time.sleep(3)
#scrapping the required details
start=0
end=60
for page in range(start,end):#for loop for scrapping 60 page
    Router_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in Router_star:
        star.append(i.text)#appending the text in Brand list
    Router_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Router_short_review:
        short_review.append(i.text)#appending the description in list
    Router_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Router_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

IndexError: list index out of range

In [158]:
#creating a dataframe
df=pd.DataFrame({'Router_star':star,
                'Router_full_review':full_review,
                'Router_short_review':short_review})
#printing dataframe
df

,Router_star,Router_full_review,Router_short_review
0,5,Best home router in this price point. signal r...,Wonderful
1,4,Honest review\n1. Flipkart service great as al...,Good choice
2,1,"Hi Everyone,\n\nSo let's talk about D-Link 819...",Very poor
3,1,I don't know what people are liking about this...,Utterly Disappointed
4,4,OK. I had searched for so many answers but did...,good wifi extender with some challenges
...,...,...,...
1166,5,Fantastic Product. Working properly. Easy inst...,Super!
1167,5,Awesome,Must buy!
1168,5,"Just osam, and range also good",Terrific
1169,5,Superb product. Nice range,Worth every penny
1170,4,"So far the speed looks good, with 2.4ghz in be...",Wonderful

In [159]:
df.to_csv("Router_comments2",index=False)

# c)

In [19]:
# opening the link
url = "https://www.flipkart.com/tp-link-archer-c50-ac1200-wireless-dual-band-1200-mbps-router/product-reviews/itmehsxsuxax7tec?pid=RTREHSXSFDYHSHHU&lid=LSTRTREHSXSFDYHSHHUMND6LX&marketplace=FLIPKART"

In [20]:
driver.get(url)

In [21]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [22]:
time.sleep(3)
#scrapping the required details
start=0
end=50
for page in range(start,end):#for loop for scrapping 50 page
    Router_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in Router_star:
        star.append(i.text)#appending the text in Brand list
    Router_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in Router_short_review:
        short_review.append(i.text)#appending the description in list
    Router_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in Router_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [23]:
#creating a dataframe
df=pd.DataFrame({'Router_star':star,
                'Router_full_review':full_review,
                'Router_short_review':short_review})
#printing dataframe
df

,Router_star,Router_full_review,Router_short_review
0,4,This router it seems is a basic gigabit router...,Good quality product
1,5,Wonderful experience so far.This provides more...,Awesome
2,5,Excellent router. Using it for a week now. The...,Just wow!
3,5,"I am a streamer as well as a gamer , this prod...",Awesome
4,5,"Really good product, very nice range at 5ghz i...",Must buy!
...,...,...,...
466,5,Working fine with 15 plus devices,Simply awesome
467,5,Nice and awesome,Fabulous!
468,5,Good at That price Buy this,Great product
469,2,Not a good coverage router,Moderate
470,5,Best,Excellent

In [24]:
df.to_excel('Router_comments3.xlsx',index=False)

# Cameras

# a)

In [29]:
# opening the link
url = "https://www.flipkart.com/canon-eos-3000d-dslr-camera-1-body-18-55-mm-lens/product-reviews/itm6f665fea97bc2?pid=CAMF3DHJURPEMNRN&lid=LSTCAMF3DHJURPEMNRNYD4BKP&marketplace=FLIPKART"

In [30]:
driver.get(url)

In [31]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [32]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 125 page
    camera_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLP'
    for i in camera_star:
        star.append(i.text)#appending the text in Brand list
    camera_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in camera_short_review:
        short_review.append(i.text)#appending the description in list
    camera_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in camera_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [33]:
#creating a dataframe
df=pd.DataFrame({'camera_star':star,
                'camera_full_review':full_review,
                'camera_short_review':short_review})
#printing dataframe
df

,camera_star,camera_full_review,camera_short_review
0,5,Well Reviewing this after using for almost one...,Great product
1,5,Worth more than the amount. Best DSLR for a go...,Just wow!
2,5,product really great . I am totally sctified t...,Excellent
3,4,The camera simply awesome..and it is a best bu...,Worth the money
4,3,Satisfied with the product.. Its a really good...,Does the job
...,...,...,...
757,5,Very good DSLR in this budget.,Mind-blowing purchase
758,5,Good to have this kind of camera,Just wow!
759,5,Awesome product thanks flipkart,Must buy!
760,5,Superb !!,Fabulous!
761,5,Rs@21700/- is best price ever..,Terrific purchase

In [34]:
df.to_excel('camera_comments1.xlsx',index=False)

## b)

In [48]:
# opening the link
url = "https://www.flipkart.com/sjcam-sj-4000-air-4k-full-hd-wifi-30m-waterproof-sports-action-camera-dv-camcorder-16mp/product-reviews/itm3f81a086c29fd?pid=SAYF956CJMBUUJFK&lid=LSTSAYF956CJMBUUJFKNMENUA&marketplace=FLIPKART"

In [49]:
driver.get(url)

In [50]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [51]:
time.sleep(3)
#scrapping the required details
start=0
end=50
for page in range(start,end):#for loop for scrapping 50 page
    camera_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in camera_star:
        star.append(i.text)#appending the text in Brand list
    camera_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in camera_short_review:
        short_review.append(i.text)#appending the description in list
    camera_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in camera_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [52]:
#creating a dataframe
df=pd.DataFrame({'camera_star':star,
                'camera_full_review':full_review,
                'camera_short_review':short_review})
#printing dataframe
df

,camera_star,camera_full_review,camera_short_review
0,5,This cam is verry good. value for money produc...,Terrific purchase
1,4,#Worth_it. Without second thought you can buy....,Worth the money
2,5,The quality and rest everything is fine but be...,Simply awesome
3,5,It's very fine for Moto vlogger and normal vid...,Must buy!
4,4,Camera clarity is so nice. But stabilization i...,Value-for-money
...,...,...,...
483,5,Nice,Simply awesome
484,4,Awesome...Action Camera in day light.,Worth the money
485,4,Fantastic,Very Good
486,5,Nyc,Awesome
487,4,Good video quality.,Good choice

In [53]:
df.to_excel('camera_comments2.xlsx',index=False)

# c)

In [41]:
# opening the link
url = "https://www.flipkart.com/canon-powershot-sx430/product-reviews/itmeqyxgbgca89nm?pid=POIEQYXGV6JQBDZQ&lid=LSTPOIEQYXGV6JQBDZQJHBOUM&marketplace=FLIPKART"

In [42]:
driver.get(url)

In [43]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [44]:
time.sleep(3)
#scrapping the required details
start=0
end=60
for page in range(start,end):#for loop for scrapping 60 page
    camera_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in camera_star:
        star.append(i.text)#appending the text in Brand list
    camera_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in camera_short_review:
        short_review.append(i.text)#appending the description in list
    camera_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in camera_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [45]:
#creating a dataframe
df=pd.DataFrame({'camera_star':star,
                'camera_full_review':full_review,
                'camera_short_review':short_review})
#printing dataframe
df

,camera_star,camera_full_review,camera_short_review
0,4,Picture quality is good. I satisfied with pict...,Worth the money
1,5,well i am a beginner so i will say its awesome...,Perfect product!
2,5,Great camera. Good zoom. Quality and color rep...,Highly recommended
3,4,good zoom is absolutely awesome but clearity i...,Nice product
4,5,At first you will not believe the images in th...,Fabulous!
...,...,...,...
594,3,Nice,Fair
595,5,it's a good product for this rate,Perfect product!
596,3,very bad performance in low light.. disappoint...,Fair
597,3,not blur in background,Does the job
598,1,No SD card,Horrible

In [46]:
df.to_excel('camera_comments3.xlsx',index=False)

# Printers

# a)

In [58]:
# opening the link
url = "https://www.flipkart.com/hp-deskjet-2331-multi-function-color-printer/product-reviews/itm5708dbe303a73?pid=PRNFTXAWZ9DZ2KHR&lid=LSTPRNFTXAWZ9DZ2KHRP7ZAXV&marketplace=FLIPKART"

In [59]:
driver.get(url)

In [60]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [61]:
time.sleep(3)
#scrapping the required details
start=0
end=65
for page in range(start,end):#for loop for scrapping 65 page
    printer_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in printer_star:
        star.append(i.text)#appending the text in Brand list
    printer_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in printer_short_review:
        short_review.append(i.text)#appending the description in list
    printer_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in printer_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [62]:
#creating a dataframe
df=pd.DataFrame({'printer_star':star,
                'printer_full_review':full_review,
                'printer_short_review':short_review})
#printing dataframe
df

,printer_star,printer_full_review,printer_short_review
0,5,Awesome product fast printing and scanning is ...,Just wow!
1,5,Excellent .. printer Hp desk jet 2331 . And yo...,Perfect product!
2,3,Ink cartridge provided with it could not print...,Good
3,3,This product is good but the paper cost very h...,Decent product
4,1,"Pathetic product, worst ever printing and scan...",Don't waste your money
...,...,...,...
471,2,"Dont buy it from flipkart, they wont help you ...",Expected a better product
472,5,Good printer,Excellent
473,2,It is useless.,Could be way better
474,5,Very good product,Great product
475,5,Nice product😍,Awesome

In [63]:
df.to_excel('Printer_comments1.xlsx',index=False)

# b)

In [64]:
# opening the link
url = "https://www.flipkart.com/hp-ink-tank-310-multi-function-color-printer/product-reviews/itmf4d6ye69qgw2g?pid=PRNF4D6YYKNZEMVX&lid=LSTPRNF4D6YYKNZEMVX7ZPC0K&marketplace=FLIPKART"

In [65]:
driver.get(url)

In [66]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [67]:
time.sleep(3)
#scrapping the required details
start=0
end=39
for page in range(start,end):#for loop for scrapping 39 page
    printer_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in printer_star:
        star.append(i.text)#appending the text in Brand list
    printer_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in printer_short_review:
        short_review.append(i.text)#appending the description in list
    printer_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in printer_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [68]:
#creating a dataframe
df=pd.DataFrame({'printer_star':star,
                'printer_full_review':full_review,
                'printer_short_review':short_review})
#printing dataframe
df

,printer_star,printer_full_review,printer_short_review
0,4,VERY NICE PRINTER ... WORKING FINE ... LOOKS A...,Pretty good
1,4,Been using this for over a month now.the bigge...,Value-for-money
2,5,"Bought it in BB sale for 7000, with exchange o...",Excellent
3,5,Onr of the best printer smooth functioning and...,Simply awesome
4,4,Printing quality is not too clear to praise. P...,Good quality product
...,...,...,...
385,4,Worth For money product,Very Good
386,5,Good,Fabulous!
387,5,super product from HP always rocks,Must buy!
388,5,good one. value for money. best buy Flipkart e...,Awesome
389,5,Value for money,Fabulous!

In [69]:
df.to_excel('Printer_comments2.xlsx',index=False)

# c)

In [70]:
# opening the link
url = "https://www.flipkart.com/hp-laserjet-pro-mfp-m126a-printer-multi-function-monochrome-laser/product-reviews/itmf3cf93180304d?pid=PRNG3FY3XVT6T8W6&lid=LSTPRNG3FY3XVT6T8W6VNWYEA&marketplace=FLIPKART"

In [71]:
driver.get(url)

In [72]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [73]:
time.sleep(3)
#scrapping the required details
start=0
end=32
for page in range(start,end):#for loop for scrapping 32 page
    printer_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in printer_star:
        star.append(i.text)#appending the text in Brand list
    printer_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in printer_short_review:
        short_review.append(i.text)#appending the description in list
    printer_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in printer_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [236]:
#creating a dataframe
df=pd.DataFrame({'printer_star':star,
                'printer_full_review':full_review,
                'printer_short_review':short_review})
#printing dataframe
df

,printer_star,printer_full_review,printer_short_review
0,5,Let's go step by step.\n\n1. The order was rec...,Excellent
1,4,been using MFP {Multi Function Printer} for ab...,"good product, worth buying"
2,5,This is the best in class from HP.... It has a...,BEST FROM HP
3,5,Wireless connectivity needs a router but you c...,Awesome product in this price range
4,4,The product is very nice. If you need only bla...,Nice product
...,...,...,...
315,5,My printer is very good,Fabulous!
316,5,Good work,Best in the market!
317,5,Nice,Worst experience ever!
318,4,Product has perform in a good manner,Value-for-money
319,5,Good product.,Awesome

In [74]:
df.to_excel('Printer_comments3.xlsx',index=False)

# d)

In [75]:
# opening the link
url = "https://www.flipkart.com/hp-ink-tank-wl-410-multi-function-wifi-color-printer-voice-activated-printing-google-assistant-alexa/product-reviews/itmf4d6y9zmndkze?pid=PRNF4D6YHFGRVD5M&lid=LSTPRNF4D6YHFGRVD5MTSPIFR&marketplace=FLIPKART"

In [76]:
driver.get(url)

In [77]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [78]:
time.sleep(3)
#scrapping the required details
start=0
end=70
for page in range(start,end):#for loop for scrapping 70 page
    printer_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in printer_star:
        star.append(i.text)#appending the text in Brand list
    printer_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in printer_short_review:
        short_review.append(i.text)#appending the description in list
    printer_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in printer_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [79]:
#creating a dataframe
df=pd.DataFrame({'printer_star':star,
                'printer_full_review':full_review,
                'printer_short_review':short_review})
#printing dataframe
df

,printer_star,printer_full_review,printer_short_review
0,4,A very good printer. Did you know that this ve...,Mind-blowing purchase
1,5,Very excellent printer.\nits working very fine...,Great product
2,5,This is my first printer. I have purchased thi...,Wonderful
3,2,some reason printer lines are shading though i...,Expected a better product
4,5,Thank you very much Flipkart / Team and Thanks...,Terrific
...,...,...,...
695,5,good,Must buy!
696,4,Very nice product.,Worth the money
697,5,Very good printer at given cost. None of any k...,Highly recommended
698,5,Amazing\nVery Good Delivery\nVery good packagi...,Simply awesome
699,5,excellent product and easy installation,Perfect product!

In [80]:
df.to_excel('Printer_comments4.xlsx',index=False)

# e)

In [86]:
# opening the link
url = "https://www.flipkart.com/canon-pixma-ts307-single-function-wifi-color-printer/product-reviews/itmb50780af949b8?pid=PRNF48UZBDBSCGQ2&lid=LSTPRNF48UZBDBSCGQ2VWNKXD&marketplace=FLIPKART"

In [87]:
driver.get(url)

In [88]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [89]:
time.sleep(3)
#scrapping the required details
start=0
end=11
for page in range(start,end):#for loop for scrapping 11 page
    printer_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in printer_star:
        star.append(i.text)#appending the text in Brand list
    printer_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in printer_short_review:
        short_review.append(i.text)#appending the description in list
    printer_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in printer_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [90]:
#creating a dataframe
df=pd.DataFrame({'printer_star':star,
                'printer_full_review':full_review,
                'printer_short_review':short_review})
#printing dataframe
df

,printer_star,printer_full_review,printer_short_review
0,5,good one with this price range and printing is...,Worth every penny
1,3,Printer is good especially fir black and white...,Fair
2,2,It work well but my printer doesn't support we...,Moderate
3,2,its been months since i bought this printer fr...,Bad quality
4,5,A very efficienct printer whith nice print qua...,Best in the market!
...,...,...,...
105,2,Printer ink gone in four days,About printer
106,1,Mobile connection is very poor,Horrible
107,4,good,Good choice
108,4,Nice...Just for emergencies,Value-for-money
109,1,not work very bad,Very poor

In [91]:
df.to_excel('Printer_comments5.xlsx',index=False)

# Smart Watches

# a)

In [96]:
# opening the link
url = "https://www.flipkart.com/apple-watch-series-3-gps-42-mm-space-grey-aluminium-case-black-sport-band/product-reviews/itm91c560e722cdd?pid=SMWF94AYMNYHTYDJ&lid=LSTSMWF94AYMNYHTYDJFOPINH&marketplace=FLIPKART"

In [97]:
driver.get(url)

In [98]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [99]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [100]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,5,Thank you for delivery it just in one day . I ...,Perfect product!
1,5,"Superb Quality , Nothing like apple , No need ...",Classy product
2,5,Apple does seem to release stable product over...,Classy product
3,5,My First Apple Watch!!! Simply Amazing.\nI use...,Terrific
4,5,Seriously I can’t express my inner feelings......,Terrific purchase
...,...,...,...
636,1,Really am disappointed with this watch dial si...,Not recommended at all
637,5,Value for money,Highly recommended
638,4,Amazing,Wonderful
639,5,Value for money.,Perfect product!
640,5,Simply super ❤️,Brilliant

In [101]:
df.to_excel('watches_comments1.xlsx',index=False)

# b)

In [102]:
# opening the link
url = "https://www.flipkart.com/dizo-watch-2-by-realme-techlife/product-reviews/itm59913ba399d56?pid=SMWG6EFSKSJGQDSK&lid=LSTSMWG6EFSKSJGQDSKVR6J0Y&marketplace=FLIPKART"

In [103]:
driver.get(url)

In [104]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [105]:
time.sleep(3)
#scrapping the required details
start=0
end=70
for page in range(start,end):#for loop for scrapping 70 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [106]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,4,Pros -\n1. Design is awesome.\n2. Build qualit...,Wonderful
1,5,Nice smartwatch...\n\nPros: nice look\nMetal b...,Must buy!
2,5,Nice good brightness also super vibration also...,Super!
3,5,Nice watch.. Pretty good looking.. not the bes...,Super!
4,5,The charger is so good with a different magnet...,Terrific purchase
...,...,...,...
283,5,Good style but sensor inappropriate.,Excellent
284,2,"So bad product Dicplay not work after 30 days,...",Not good
285,5,Nice very Premium metal body,Super!
286,5,Really best watch,Brilliant
287,5,Nice,Terrific purchase

In [107]:
df.to_excel('watches_comments2.xlsx',index=False)

# c)

In [108]:
# opening the link
url = "https://www.flipkart.com/realme-watch-2/product-reviews/itm44d90218d1891?pid=SMWG4WFWZABX4VQF&lid=LSTSMWG4WFWZABX4VQFXF6IVW&marketplace=FLIPKART"

In [109]:
driver.get(url)

In [110]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [111]:
time.sleep(3)
#scrapping the required details
start=0
end=100
for page in range(start,end):#for loop for scrapping 100 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [112]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,5,First day first sale product and the watch is ...,Worth every penny
1,5,This is value for money and good watch and bri...,Wonderful
2,5,Nice watch good brightness durable and reliabl...,Perfect product!
3,5,perfect watch at this price segment\namazing d...,Highly recommended
4,5,My most favorite 😍 very good and screen is als...,Terrific purchase
...,...,...,...
563,4,Nice,Delightful
564,4,Must buy,Nice product
565,5,Good,Fabulous!
566,5,Nice watch 😊😊😊✌️,Wonderful
567,5,Its such a nyc watch..look is so awsome ... al...,Worth every penny

In [113]:
df.to_excel('watches_comments3.xlsx',index=False)

# d)

In [124]:
# opening the link
url = "https://www.flipkart.com/boat-storm-smartwatch/product-reviews/itm215a48c547168?pid=SMWG3EC4KCEFNNKH&lid=LSTSMWG3EC4KCEFNNKHJXJOIN&marketplace=FLIPKART"

In [125]:
driver.get(url)

In [126]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [127]:
time.sleep(3)
#scrapping the required details
start=0
end=30
for page in range(start,end):#for loop for scrapping 30 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [128]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,4,Writing this review after 2 weeks.\nPROS:-less...,Good choice
1,5,Wooww🖤Grt watch\nawesome 💌💌\n🖤I loved it super...,Worth every penny
2,3,Been using this Watch since it's launch. 30th ...,Does the job
3,4,Boat smart watch nice and decent product in th...,Delightful
4,4,Ya its a cool watch and I liked the built qual...,Nice product
...,...,...,...
295,4,Nice product,Worth the money
296,1,Watch is ok but I m not happy with flipkart re...,Unsatisfactory
297,1,False data provided by Blood Pressure monitori...,Horrible
298,1,Worst services of flipkart\nAnd this watch is ...,Don't waste your money
299,3,"Bluetooth connectivity issue with devise , alw...",Decent product

In [129]:
df.to_excel('watches_comments4.xlsx',index=False)

# e)

In [134]:
# opening the link
url = "https://www.flipkart.com/apple-watch-series-3-gps-38-mm-silver-aluminium-case-fog-sport-band/product-reviews/itm98a0bb70c4cd3?pid=SMWF94AYS96GPYRM&lid=LSTSMWF94AYS96GPYRM9MUBC2&marketplace=FLIPKART"

In [135]:
driver.get(url)

In [136]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [137]:
time.sleep(3)
#scrapping the required details
start=0
end=90
for page in range(start,end):#for loop for scrapping 140 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [138]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,5,Thank you for delivery it just in one day . I ...,Perfect product!
1,5,"Superb Quality , Nothing like apple , No need ...",Classy product
2,5,Apple does seem to release stable product over...,Classy product
3,5,My First Apple Watch!!! Simply Amazing.\nI use...,Terrific
4,5,Seriously I can’t express my inner feelings......,Terrific purchase
...,...,...,...
882,5,"Best product with great discounts,thanks Flipk...",Perfect product!
883,4,Good products,Worth the money
884,5,Amazing product,Super!
885,5,It's amazing,Classy product
886,5,Such a really osam product,Must buy!

In [139]:
df.to_excel('watches_comments5.xlsx',index=False)

# f)

In [140]:
# opening the link
url = "https://www.flipkart.com/e-live-dz09-4g-calling-health-notifier-smartwatch/product-reviews/itm10cd5354c10c7?pid=SMWF4ZCZXT24VU9X&lid=LSTSMWF4ZCZXT24VU9XVYOVYW&marketplace=FLIPKART"

In [141]:
driver.get(url)

In [142]:
#creating the empty list
star=[]
full_review=[]
short_review=[]

In [143]:
time.sleep(3)
#scrapping the required details
start=0
end=80
for page in range(start,end):#for loop for scrapping 80 page
    watches_star=driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]")#scraping brands name by class name='col _2wzgFH K0kLPL'
    for i in watches_star:
        star.append(i.text)#appending the text in Brand list
    watches_short_review=driver.find_elements_by_xpath("//p[@class='_2-N8zT']")#scraping description from the xpath
    for i in watches_short_review:
        short_review.append(i.text)#appending the description in list
    watches_full_review=driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div")# scraping the price from the xpath
    for i in watches_full_review:
        full_review.append(i.text)
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")#scraping the list of buttons from the page
    try:
        driver.get(nxt_button[1].get_attribute('href'))#getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [144]:
#creating a dataframe
df=pd.DataFrame({'watches_star':star,
                'watches_full_review':full_review,
                'watches_short_review':short_review})
#printing dataframe
df

,watches_star,watches_full_review,watches_short_review
0,5,Its awesome watch and it is very useful batter...,Great product
1,5,Best smart watch but battery power is low I wi...,Excellent
2,3,Ahe product was good but battery backup is Not...,Decent product
3,5,super and fantastic mobile watch thanks Flipkart,Terrific purchase
4,5,Thanks you so much,Terrific purchase
...,...,...,...
795,5,nice product,Terrific purchase
796,1,very bed watch,Not recommended at all
797,5,so nice watch but no wifi no internet,Terrific purchase
798,5,Good,Super!
799,1,battery damage,Don't waste your money

In [145]:
df.to_excel('watches_comments6.xlsx',index=False)